### ISSUE TITLE
Please tag new releases more regulary

### ISSUE THREAD

**Issue by pkramme** [shopware/opentelemetry#9]
Hello together, 

thanks for your awesome work on this plugin! We are actively testing with this and are seeing positive results. I'd like to ask you to tag more regular dev versions of this project, so that feedback can be more targeted at specific versions. 

Would that be possible? 

Thank you very much!

**Comment by h1k3r** [comment]
Hi @pkramme,

Thank you so much for your interest and for bringing this up! 🙌

You’re absolutely right—there are indeed some commits that haven't been tagged yet: https://github.com/shopware/opentelemetry/compare/0.1.4...main.

The latest changes in this repository are dependent on the newly added abstractions in the Shopware Core: https://github.com/shopware/shopware/tree/trunk/src/Core/Framework/Telemetry.

We’re currently waiting for the next version of Shopware to be released so we can test these changes. After that, we’ll go ahead and tag the latest commits.

Thanks again for your patience!

**Comment by pkramme** [comment]
I understand! Would it be possible to tag 5eb46ad9161acc78d53bd4de7009667d809763f1 as latest release? This commit is the last version that we can run on Shopware 6.5.8.x, and it fixes/supports a few important things like Opensearch queries and better spans.

It would allow me to drop my pkramme/opentelemetry fork where I tagged that commit as 99.0.0 and would allow devs to use `composer require shopware/opentelemetry` correctly.

**Comment by h1k3r** [comment]
No worries, I’ve just tagged that commit as a new release. Here’s the [link](https://github.com/shopware/opentelemetry/releases/tag/0.1.5)

If you run into any issues, please let us know!

**Comment by pkramme** [comment]
Thank you so much!
